const actionTypes ={
    LOGIN:'LOGIN',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    REGISTER: 'REGISTER',
    REGISTER_SUCCESS:'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',

    LOGOUT:'LOGOUT',

    ADD:'ADD',
    ADD_SUCCESS:'ADD_SUCCESS',
    ADD_FAIL: 'ADD_FAIL',

    GET:'GET',
    GET_SUCCESS:'GET_SUCCESS',
    GET_FAIL: 'GET_FAIL',

    GET_ALL:'GET_ALL',
    GET_ALL_SUCCESS:'GET_ALL_SUCCESS',
    GET_ALL_FAIL: 'GET_ALL_FAIL',

    UPDATE:'UPDATE',
    UPDATE_SUCCESS:'UPDATE_SUCCESS',
    UPDATE_FAIL: 'UPDATE_FAIL',

    DELETE:'DELETE',
    DELETE_SUCCESS:'DELETE_SUCCESS',
    DELETE_FAIL: 'DELETE_FAIL',

    FILTER_BY_NAME: 'SEARCH_BY_NAME',
    FILTER_BY_COLLECTION: 'FILTER_BY_COLLECTION',
    FLITER_BY_COLORS: 'FLITER_BY_COLOR',
    FILTER_BY_PRICE: 'FILTER_BY_PRICE',
    SORT: 'SORT',

}

export default actionTypes;